/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package offline1_1;

import offline1_1.Builder.*;

public class App {
    public static void main(String[] args) {
        PCBuilder pcb = new Type3PCBuilder();
        pcb.initPC();
        PC pc = pcb.getPC();
        System.out.println(pc);
    }
}
