/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package abccompany;

public class App {
    public static void main(String[] args) {
        Server server =  new Server();

        PremiumUser user1 = new PremiumUser(server, "premium");
        RegularUser user2 = new RegularUser(server, "regular");

        server.setState("O");
        server.setState("P");
        server.setState("F");

    }
}
