/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package examcontroller;

import java.util.Scanner;

public class App {
    private static Scanner scn = new Scanner(System.in);

    public static void main(String[] args) {
        int[] marks = {95, 90, 93, 90, 96};
        ExamController examController = new ExamController();

        Examiner examiner = new Examiner(examController, marks);
        Student[] students =  new Student[5];
        for(int i = 0; i < 5; i++){
            students[i] = new Student(i+1, examController);
        }

        examController.setExaminer(examiner);
        examController.setStudents(students);


        examiner.sendMarks();

        System.out.println("Recheck student id");
        int id = scn.nextInt();
        students[id-1].sendRecheckRequest();
    }
}
