/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package offline1_2;

import java.util.Scanner;

public class App {  
    static Scanner scanner = new Scanner(System.in);

    static CarManufacturer getCarManufacturer(String continent){
        if(continent.equalsIgnoreCase("asia")) return new ToyotaCarManufacturer();
        else if(continent.equalsIgnoreCase("europe")) return new BMWCarManufacturer();
        else if(continent.equalsIgnoreCase("us")) return new TeslaCarManufacturer();
        return null;
    }

    public static void main(String[] args) {
        System.out.println("Enter Your Continent: ");
        String continent = scanner.next();
        

        CarManufacturer man = getCarManufacturer(continent);
        if(man == null){
            System.out.println("Sorry no car available for your region");
            return ;
        }
        man.manufacture();
    }
}
